In [8]:
#import libraries
import numpy as np
import pandas as pd
import requests

### Scraping Table from Wikipedia page

In [39]:
page = requests.get('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')
df_list = pd.read_html(page.content)
df_list
df = df_list[0]
df.to_csv('toronto_data.csv')

### Transforming into *pandas* Dataframe

In [40]:
toronto_df = pd.read_csv('toronto_data.csv')
toronto_df.head()

   Unnamed: 0 Postal Code           Borough              Neighbourhood
0           0         M1A      Not assigned               Not assigned
1           1         M2A      Not assigned               Not assigned
2           2         M3A        North York                  Parkwoods
3           3         M4A        North York           Victoria Village
4           4         M5A  Downtown Toronto  Regent Park, Harbourfront

### Data cleaning

In [41]:
toronto_df.drop('Unnamed: 0', axis=1, inplace=True)

#### drop rows with 'Not assigned' borough

In [42]:
toronto_df.replace('Not assigned', np.nan, inplace = True)
toronto_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Postal Code    180 non-null    object
 1   Borough        103 non-null    object
 2   Neighbourhood  103 non-null    object
dtypes: object(3)
memory usage: 4.3+ KB

#### check result

In [43]:
toronto_df.dropna(subset=['Borough'], axis=0, inplace=True)
toronto_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103 entries, 2 to 178
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Postal Code    103 non-null    object
 1   Borough        103 non-null    object
 2   Neighbourhood  103 non-null    object
dtypes: object(3)
memory usage: 3.2+ KB

#### formatting

In [44]:
toronto_df.reset_index(inplace=True, drop=True)
toronto_df.head()

  Postal Code           Borough                                Neighbourhood
0         M3A        North York                                    Parkwoods
1         M4A        North York                             Victoria Village
2         M5A  Downtown Toronto                    Regent Park, Harbourfront
3         M6A        North York             Lawrence Manor, Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

#### check shape of dataframe

In [45]:
toronto_df.shape

(103, 3)

## Step2 - Get the geographical coordinates of the neighborhoods

In [46]:
!wget -q -O 'coordinates.csv' https://cocl.us/Geospatial_data

In [47]:
coor_df = pd.read_csv('coordinates.csv')
coor_df.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

#### merge two dataframes

In [55]:
toronto_df_co = pd.merge(toronto_df, coor_df,how='inner', on='Postal Code')
print(toronto_df_co.info())
toronto_df_co.head(10)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103 entries, 0 to 102
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Postal Code    103 non-null    object
 1   Borough        103 non-null    object
 2   Neighbourhood  103 non-null    object
 3   Latitude       103 non-null    float64
 4   Longitude      103 non-null    float64
dtypes: float64(2), object(3)
memory usage: 4.8+ KB
None

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
5,M9A,Etobicoke,"Islington Avenue, Humber Valley Village",43.667856,-79.532242
6,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
7,M3B,North York,Don Mills,43.745906,-79.352188
8,M4B,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
9,M5B,Downtown Toronto,"Garden District, Ryerson",43.657162,-79.378937